steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
    - 'DOCKER_BUILDKIT=1'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/g41-registry/api',
    '--cache-from', 'europe-west1-docker.pkg.dev/$PROJECT_ID/g41-registry/api:latest',
    '-f', 'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/g41-registry/api'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'g41-service',
    '--image',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/g41-registry/api',
    '--region', 'europe-west1',
    '--platform', 'managed',
    # optional argument if you want to inject secrets as environment variables
    '--update-secrets=WANDB_API_KEY=WANDB_API_KEY:latest',
    '--set-env-vars=WANDB_ARTIFACT_PATH=wandb-registry-Ticket Urgency/models:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
